@baseURL = http://localhost:8081/produtos

### Listar todos os produtos
GET {{baseURL}}

###BUSCAR UM PRODUTO PELO ID
GET {{baseURL}}/999

### Criar um produto
POST {{baseURL}}
Content-Type: application/json

{
  "nome": "Produto qualquer",
  "descricao": "Notebook Dell  15'17, 16GB RAM, RAM 1TB",
  "preco": 0
}

### Atualizar um produto
PUT {{baseURL}}/3
Content-Type: application/json

{
  "nome": "Notebook Dell",
  "descricao": "Notebook Dell  15'17, 16GB RAM, RAM 1TB",
  "preco": 7999.90
}

### Deletar um produto
DELETE {{baseURL}}/1